name: smartkyc
description: "A Robust Solution to KYC"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  http: ^1.3.0
  flutter_native_splash: ^2.4.4
  flutter_bloc: ^9.0.0
  go_router: ^14.6.3
  smooth_page_indicator: ^1.2.0+3
  equatable: ^2.0.7
  camera: ^0.11.0+2
  get_it: ^8.0.3
  lottie: ^3.3.1
  flutter_animate: ^4.5.2
  intl: ^0.19.0
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1
  flutter_launcher_icons: ^0.14.3
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  pinput: ^5.0.1
  formz: ^0.8.0
  email_validator: ^3.0.0
  path: ^1.9.0
  path_provider: ^2.1.5
  firebase_storage: ^12.4.1
  shared_preferences: ^2.4.0
  cloud_firestore: ^5.6.2
  package_info_plus: ^8.1.4
  flutter_gen: ^5.8.0
  local_auth: ^2.3.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  flutter_dotenv: ^5.2.1
  tflite_flutter: ^0.11.0
  image: ^4.5.2
  amplify_auth_cognito: ^2.6.0
  amplify_core: ^2.6.0
  amplify_flutter: ^2.6.0

dependency_overrides:
  # Force firebase_storage_web and firebase_auth_web to use any version
  firebase_storage_web: any
  firebase_auth_web: any
  # Override the 'web' package to ^1.0.0 so it satisfies firebase_auth_web;
  # This should be safe on mobile, even if drift expects web ^0.5.0.
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_screen_logo.png
  android_12:
    image: assets/images/splash_screen_logo.png
    color: "#ffffff"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/driving_liscense_spicemen.jpg
    - assets/lottie/checkmark.json
    - assets/lottie/verify_email.json
    - assets/lottie/delete.json
    - assets/lottie/verification_progress_overlay.json
    - assets/lottie/verification_success.json
    - assets/.env
    - assets/model/nepali_license_detector.tflite

flutter_icons:
  android: true
  image_path: "assets/images/app-icon.png"
  adaptive_icon_foreground: "assets/images/app-icon.png"
  adaptive_icon_background: "#ffffff"
