name: smartkyc
description: "A Robust Solution to KYC"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  http: ^1.2.1
  flutter_native_splash: ^2.4.4
  flutter_bloc: ^9.0.0
  go_router: ^14.6.3
  smooth_page_indicator: ^1.2.0+3
  equatable: ^2.0.7
  camera: ^0.11.0+2
  get_it: ^8.0.3
  lottie: ^3.3.1
  flutter_animate: ^4.5.2
  intl: ^0.20.1
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_screen_logo.png
  android_12:
    image: assets/images/splash_screen_logo.png
    color: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/driving_liscense_spicemen.jpg

flutter_icons:
  android: true
  image_path: "assets/images/app-icon.png"
  adaptive_icon_foreground: "assets/images/app-icon.png"
  adaptive_icon_background: "#ffffff"
